#FROM openjdk:11-jdk
FROM openjdk:17-jdk
COPY ./Hello.class /
CMD ["java","Hello"]



#########################################
## Docker commands:
# cd dockerfile-demos/hello/
# javac Hello.java

# docker build -t hello .
# docker run --name hello-app hello

