# alpine images is the basic image example, just to start playing around with docker
#slimmed image of a linux OS   " A minimal Docker image based on Alpine Linux with a complete package index and only 5 MB in size! "
# https://hub.docker.com/_/alpine
FROM alpine
CMD ["ls"]



#########################################
## Docker commands:
# cd dockerfile-demos/os/
# docker build .
# docker images # to see the list of images and take the image id fo rnext command

# docker run --name os-app 300d984d3476
#                           <image id>

## list containers
# docker ps -a

##list images
# docker images

## remove container
# docker rm os-app
# docker ps -a


## remove image
# docker rmi 300d984d3476
# docker images
